DROP TABLE IF EXISTS `ADMIN`;
CREATE TABLE `ADMIN`(
	`ADMIN_ID`   int NOT NULL AUTO_INCREMENT,	
	`ADMIN_USERID`      char(30) NOT NULL,
	`ADMIN_PASSWORD`    char(100) NOT NULL,
	`ADMIN_USERNAME`    char(100) NOT NULL,
	`ADMIN_NICKNAME`    char(8) NOT NULL,
	`ADMIN_MOBILEPHONE` char(20) NOT NULL,
	`ADMIN_EMAIL`       char(50)NOT NULL,

 	PRIMARY KEY(`ADMIN_ID`)
) AUTO_INCREMENT=1;

INSERT INTO `ADMIN` (`ADMIN_ID`, `ADMIN_USERID`, `ADMIN_PASSWORD`, `ADMIN_USERNAME`, `ADMIN_NICKNAME`, `ADMIN_MOBILEPHONE`, `ADMIN_EMAIL`) VALUES (1, 'st23', 'c9st23', '지효남', '관리자', '01087346373', 'hks4919@gamil.com');
