DROP TABLE IF EXISTS `LOLMARKET`;
CREATE TABLE `LOLMARKET`(
	`CONTROLOR_KEY`   INT NOT NULL AUTO_INCREMENT,	
	`PRODUCT`      CHAR(30) NOT NULL,
	`PRODUCT_COLOR`    CHAR(30) NOT NULL,
	`PRODUCT_VALUE`    INT NOT NULL,
	`PRODUCT_OPCTION`  CHAR(30),
	`PRODUCT_PRICE`    INT NOT NULL,

 	PRIMARY KEY(`CONTROLOR_KEY`)
) AUTO_INCREMENT=1;
